### ISSUE TITLE
ACL resources fail to be created

### ISSUE THREAD

**Issue by dangbert** [hashicorp/learn-terraform-modules-create#14]
The created bucket seems to have ACLs disabled, so terraform fails with AccessDenied after creating the bucket and attempting to set ACL configs.

![image](https://github.com/hashicorp/learn-terraform-modules-create/assets/6439020/01e24b10-380f-492e-9a41-1bada2d26174)

["learn more" links here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html?icmpid=docs_amazons3_console)

<img width="839" alt="image" src="https://github.com/hashicorp/learn-terraform-modules-create/assets/6439020/42856cc2-6e18-4ab9-9f65-a30912ce9486">

I will look into this, but please advise if possible thanks!

**Comment by dangbert** [comment]
Probably related to this https://github.com/hashicorp/terraform-provider-aws/issues/762

**Comment by vpipkt** [comment]
I had the same issue and found that the s3 model around ACLs has grown more complex and thus we need to create more resources to create the ACL.  

https://github.com/hashicorp/learn-terraform-modules-create/pull/12 fixes this issue for me
